import json

# Load this from a file instead of putting it here (like config in example)
config_file = 'baxter_dqn_config.json'

class DQNConfig():
    def __init__(self):
        self.experiments = experiments

    def load_config(self):
        with open(config_file, 'r') as fp:
            experiments = json.load(fp)

    def save_config(self):
        with open(config_file, 'w') as fp:
            json.dump(experiments, fp)

    def add_field(field_name):
        for d in experiments:
            d[field_name] = None

    def add_experiment(item):
        learning_rate = [0.05, 0.0025]
        memory_size = [2000]
        gamma = [0.99, 0.85]
        replay_mem_update_freq = [10000, 20000, 50000]
        replay_mem_init_size = [50000]
        loss_function = ['mse', 'huber']
        optimizer = ['adam', 'RMSProb']
        experiments.append(item)

    def print_config(self):
        print(self.experiments)

experiments = [
    {'name': 'exp0',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp1',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'torus_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp2',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'huber',
     'optimizer': 'RMSprob',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp3',
     'learning_rate': 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'huber',
     'optimizer': 'RMSprob',
     'reward': 'torus_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp4',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.85,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp5',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 20000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp6',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp7',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.995,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp8',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'torus_distance',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp9',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp10',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.85,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp11',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.85,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'line_distance',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp12',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.85,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'torus_distance',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp13',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.85,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'torus_distance',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp14',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp15',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp16',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp17',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': False,
     'action_type': 'single'
     },
    {'name': 'exp18',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': False,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp19',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': False,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp20',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': False,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp21',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': False,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp22',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp23',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp24',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp25',
     'learning_rate' : 0.0025,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 50000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 1000,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': 'end_effector'
     },
    {'name': 'exp26',
     'learning_rate' : 0.05,
     'memory_size': 200000,
     'gamma': 0.99,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 50000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D'
     },
    {'name': 'exp27',
     'learning_rate' : 0.001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 64,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D'
     },
    {'name': 'exp28',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 64,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D'
     },
    {'name': 'exp29',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 128,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D'
     },
    {'name': 'exp30',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 128,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D'
     },
    # Pure exploration test for zone stats
    {'name': 'exp31',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 10000,
     'epsilon_decay': 0,
     'epsilon_guided': False,
     'batch_size': 32,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D'
     },
    # Started using zone queues here
    {'name': 'exp32',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 64,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D',
     'zone_queue': True,
     'zone_dist': None
     },
    {'name': 'exp33',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 64,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D',
     'zone_queue': True,
     'zone_dist': [0.4, 0.3, 0.2, 0.1]
     },
    {'name': 'exp34',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 64,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D',
     'zone_queue': True,
     'zone_dist': [0.1, 0.2, 0.3, 0.4]
     },
    {'name': 'exp35',
     'learning_rate' : 0.0001,
     'memory_size': 200000,
     'gamma': 0.999,
     'replay_mem_update_freq': 10000,
     'replay_mem_init_size': 200000,
     'loss_function': 'mse',
     'optimizer': 'adam',
     'reward': 'advanced_sparse_reward',
     'randomPos': True,
     'epsilon_start': 500,
     'epsilon_decay': 0.9977,
     'epsilon_guided': False,
     'batch_size': 64,
     'model': "3layer_LH",
     'torusCollision': True,
     'action_type': '2D',
     'zone_queue': True,
     'zone_dist': [0.2, 0.4, 0.2, 0.2]
     },
]